### PR TITLE
Delete this

### PR DESCRIPTION
**Pull request by dopoi16**
I think that we should think what will be here

### CODE REVIEW

**Review by dopoi16 — COMMENTED** [review]
I have checked all the information I submitted. Can @fedKotikeD please check my PR and write a review as a code owner? If you do not understand why I want to do these edits you can ask me. Thank you!

**Review by fedKotikeD — CHANGES_REQUESTED** [review]
Please, report me why you want to do this actions. My Discord: Dmitriy Nero#4843

**Comment by dopoi16** [comment]
But, okay. I think that we should think what will be in this repository. But there are only three stupid files. You can download all the files from official source or delete this at some time.

**Review by fedKotikeD — APPROVED** [review]
Okay, so be it. So far, I will approve the PR, and it will be merged, but if you need to add new files later, throw a new PR. I hope that we have not suffered serious losses, merge will be now!

**Comment by dopoi16** [comment]
Thank you a lot

**Pull request merged**
