### PR TITLE
Grand remake

### PR DESCRIPTION
**Pull request by dopoi16**
It seems to me that you need to redo all the files for files from the official source

### CODE REVIEW

**Comment by dopoi16** [comment]
Now I will make all the deletion commits and add new files somewhere at 20:00

**Comment by dopoi16** [comment]
Yay! That's it. After a huge amount of time, I was able to delete all the files. Now I'll go home from work and upload new files. Also waiting for code owner response!

**Review by fedKotikeD — CHANGES_REQUESTED** [review]
I'm still waiting for files to be added

**Comment by fedKotikeD** [comment]
This is a great job you have done. Thanks a lot. I look forward to completion PR and will gladly add it when it's ready! Good luck to you!

**Comment by fedKotikeD** [comment]
I speak for those who do not see. This person wrote to me in the discord in DM and said that due to technical problems he could not add everything. I'll try and close the PR

**Review by fedKotikeD — APPROVED** [review]
After some technical problems, I can say: the files are placed correctly and I can confirm everything!

**Pull request merged**
